Added missing instances: Semigroup Monoid Alternative
input-output-hk/cardano-base pull request #314
Opened 2022-10-07 13:12 UTC by TimSheard

Added a few missing instances that are there for Maybe and should be there for StrictMaybe as well.

2022-10-07 13:34 UTC, lehins requested changes
Implementation looks good, just some minor issues with formatting

2022-10-07 13:34 UTC, lehins commented on strict-containers/src/Data/Maybe/Strict.hs
> +    l        <|> _ = l
Indentation is off and trailing newline
```suggestion
instance Alternative StrictMaybe where
  empty = SNothing
  SNothing <|> r = r
  l        <|> _ = l

```

2022-10-07 13:34 UTC, lehins commented on strict-containers/src/Data/Maybe/Strict.hs
> +  (SJust x) <> (SJust y) = SJust(x <> y)
Redundant parenthesis and a missing space
```suggestion
  SJust x <> SJust y = SJust (x <> y)
```

2022-10-27 21:48 UTC, TimSheard commented
OK, ready for another review.

2022-10-27 22:11 UTC, lehins approved these changes
Looks great. Thank you

2022-10-28 18:54 UTC, merged