BLS test vectors
input-output-hk/cardano-base pull request #408
Opened 2023-05-08 16:33 UTC by tdammers

Integrate Rust test vectors with the Haskell BLS code and test suite.

2023-05-12 18:16 UTC, lehins requested changes
Looks good. Just a few comments

2023-05-15 16:43 UTC, lehins commented
It's quite peculiar.
@tdammers and @iquerejeta do you guys know why are the tests failing on Windows?
In particular, is it a problem with tests or the actual implementation?

2023-05-16 07:57 UTC, tdammers commented
> @tdammers and @iquerejeta do you guys know why are the tests failing on Windows?
In particular, is it a problem with tests or the actual implementation?

I think I know.

The error originates in `Base16.decode`, specifically [here](https://hackage.haskell.org/package/base16-bytestring-1.0.2.0/docs/src/Data.ByteString.Base16.html#decode); it occurs when the length of the bytestring to be decoded is not even (which it has to be because each byte encodes to two hex digits).

And the reason it is uneven on Windows is because (as per review comment) we now use ByteString IO instead of String IO and `lines` from `Data.ByteString.Char8` instead of the `Prelude` one on `String`. My hypothesis is that it goes like this:

- git on the Windows CI machines is configured to automatically convert line endings on checkout (I think that's the default on Windows), so the hex files have `\r\n` line endings on Windows CI, but plain `\n` on Linux and OSX.
- We then open the file in binary mode (`Data.ByteString.readFile`; previously this was `System.IO.readFile`, which uses text mode), so the `\r` is retained.
- `Data.ByteString.Char8.lines` then splits on `\n`; it does not consider `\r` to be a newline character, and does not strip it away.
- The bytestring we feed to `Data.ByteString.Base16.decode` now has a trailing `\r` attached to it on Windows (but not on the other OSes, where git does not inject `\r`, because plain `\n` is the native line ending convention).

2023-05-16 14:24 UTC, tdammers commented on cardano-crypto-tests/cardano-crypto-tests.cabal
> +data-files: bls12-381-test-vectors/test_vectors/*
I've gone with the "list them all individually" solution, at least for now.

2023-05-16 19:54 UTC, lehins commented
@tdammers Oh yeah, Windows newline strikes again. I always forget about it. In that case we can go back to using `String` for reading and splitting on newlines: `map BS8.pack . Prelude.lines <$> Prelude.readFile f`. Hex decoding still needs to be done on ByteStrings.

>  line-split (still on Text), 

I thought about the same thing, but unfortunately `text` package also ignores the CR character, from haddock: "[lines](https://www.stackage.org/haddock/nightly-2023-05-16/text-2.0.2/Data-Text.html#v:lines) does not treat '\r' (CR, carriage return) as a newline character."

2023-05-17 19:48 UTC, lehins approved these changes
LGTM

2023-05-17 19:48 UTC, lehins commented on cardano-crypto-class/cardano-crypto-class.cabal
> +  c-sources: cbits/blst_util.c
This has already been added. See line 127 https://github.com/input-output-hk/cardano-base/blob/f855e4b571de47865341590196b712c7e20cf0d0/cardano-crypto-class/cardano-crypto-class.cabal#L127
```suggestion
```

2023-05-17 19:50 UTC, lehins commented
> Bottom line, just stripping \r like I did in the last commit is probably the sanest solution here.

Yeah, sounds reasonable.

2023-05-18 06:22 UTC, angerman commented on cardano-crypto-class/cardano-crypto-class.cabal
> +                    cbits/blst_util.c
```suggestion
```
This seems suspicious? It's listed under c-sources already.

2023-05-18 07:30 UTC, merged