Checked `StrictMVar`s and `StrictTVar`s
input-output-hk/cardano-base pull request #423
Opened 2023-07-10 11:10 UTC by jorisdral

This PR moves checked versions of `StrictMVar` and `StrictTVar` to `cardano-base`.

Related PRs:
* https://github.com/input-output-hk/io-sim/pull/108
* https://github.com/input-output-hk/io-sim/pull/109

2023-07-10 11:13 UTC, jorisdral commented on cabal.project
> +    strict-mvar
`strict-mvar-1.1.0.0` doesn't export `LazyMVar` yet, but it should in a next version

2023-07-17 18:56 UTC, lehins commented
What is the plan for`strict-checked-vars`, will it be released to hackage or CHaP?

2023-07-27 08:35 UTC, coot requested changes
Thanks @jorisdral.

2023-07-27 08:35 UTC, coot commented on strict-checked-vars/src/Control/Concurrent/Class/MonadMVar/Strict/Checked.hs
> +modifyMVarMasked_ v io = modifyMVar v io'
```suggestion
modifyMVarMasked_ v io = modifyMVarMasked v io'
```

2023-07-27 08:35 UTC, coot commented on strict-checked-vars/strict-checked-vars.cabal
> +  location: https://github.com/input-output-hk/ouroboros-consensus
```suggestion
  location: https://github.com/input-output-hk/cardano-base
```

2023-07-27 08:35 UTC, coot commented on strict-checked-vars/strict-checked-vars.cabal
> +bug-reports:     https://github.com/input-output-hk/io-sim/issues
```suggestion
bug-reports:     https://github.com/input-output-hk/cardano-base/issues
```

2023-07-27 08:35 UTC, coot commented on strict-checked-vars/strict-checked-vars.cabal
> +    -Wpartial-fields -Widentities
I suspect that `-Wno-unticked-promoted-constructors` is not really needed.  In `io-classes` we use these flags:
```
    ghc-options: -Wall
                 -Wcompat
                 -Wincomplete-uni-patterns
                 -Wincomplete-record-updates
                 -Wpartial-fields
                 -Widentities
                 -Wunused-packages
                 -Wno-redundant-constraints
                 -Wno-unticked-promoted-constructors
```

2023-07-27 08:35 UTC, coot commented on strict-checked-vars/strict-checked-vars.cabal
> +    -Wpartial-fields -Widentities -fno-ignore-asserts
as above

2023-07-31 09:17 UTC, coot approved these changes
LGTM

2023-07-31 12:21 UTC, merged